// Generated by gencpp from file sauvc/lokasi.msg
// DO NOT EDIT!


#ifndef SAUVC_MESSAGE_LOKASI_H
#define SAUVC_MESSAGE_LOKASI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sauvc
{
template <class ContainerAllocator>
struct lokasi_
{
  typedef lokasi_<ContainerAllocator> Type;

  lokasi_()
    : xloc(0)  {
    }
  lokasi_(const ContainerAllocator& _alloc)
    : xloc(0)  {
  (void)_alloc;
    }



   typedef uint8_t _xloc_type;
  _xloc_type xloc;





  typedef boost::shared_ptr< ::sauvc::lokasi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sauvc::lokasi_<ContainerAllocator> const> ConstPtr;

}; // struct lokasi_

typedef ::sauvc::lokasi_<std::allocator<void> > lokasi;

typedef boost::shared_ptr< ::sauvc::lokasi > lokasiPtr;
typedef boost::shared_ptr< ::sauvc::lokasi const> lokasiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sauvc::lokasi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sauvc::lokasi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sauvc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/melodic/share/geographic_msgs/cmake/../msg'], 'sauvc': ['/home/amvui/sauvc_ws/src/sauvc2020/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/melodic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/melodic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::lokasi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sauvc::lokasi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::lokasi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sauvc::lokasi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::lokasi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sauvc::lokasi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sauvc::lokasi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82f34519e751e2caec3eadc7bc50234e";
  }

  static const char* value(const ::sauvc::lokasi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82f34519e751e2caULL;
  static const uint64_t static_value2 = 0xec3eadc7bc50234eULL;
};

template<class ContainerAllocator>
struct DataType< ::sauvc::lokasi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sauvc/lokasi";
  }

  static const char* value(const ::sauvc::lokasi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sauvc::lokasi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 xloc\n"
;
  }

  static const char* value(const ::sauvc::lokasi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sauvc::lokasi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xloc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lokasi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sauvc::lokasi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sauvc::lokasi_<ContainerAllocator>& v)
  {
    s << indent << "xloc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.xloc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAUVC_MESSAGE_LOKASI_H
